In [2]:
print("Hello World")

Hello World


In [10]:
#Start Numpy
import numpy as np

In [19]:
data = [1,2,3,4,5] #Data list
data

[1, 2, 3, 4, 5]

In [20]:
np.array(data) #Mengubah list menjadi numpy array

array([1, 2, 3, 4, 5])

In [21]:
np.arange(0,10) #Membuat data array numpy secara otomatis 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(0,10,2) #2 merupakan kelipatan

array([0, 2, 4, 6, 8])

In [23]:
#Membuat array dummy
np.linspace(0,10,3)  #0 batas awal, 10 batas akhir, 3 jumlah data ada 3

array([ 0.,  5., 10.])

In [28]:
 np.linspace(0,10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [29]:
#Membuat array secara random
np.random.rand(3) #3 jumlah data dumy

array([0.20851067, 0.32616887, 0.43385396])

In [30]:
np.random.rand(5,3) #5 baris 3 kolom

array([[0.29607129, 0.47990791, 0.41440258],
       [0.74832578, 0.64261811, 0.96587219],
       [0.50637285, 0.67211434, 0.22510048],
       [0.09447153, 0.89986492, 0.88005912],
       [0.87168779, 0.95500578, 0.62421433]])

In [33]:
#Membuat data array random secara negatif dan positif
np.random.randn(3,2) #n ada data - didumy

array([[-0.32932417,  0.88950855],
       [ 0.86111688, -0.33013495],
       [ 1.84906401,  0.58065717]])

In [35]:
#Membuat data array random bilangan bulat
np.random.randint(1,50) #Menghitung rangenya data random

19

In [37]:
np.random.randint(1,50,10)

array([40,  2, 30,  4, 25,  4, 18, 23, 28, 37])

In [27]:
#Merubah tampilan array perbaris dan kolom

#Array 1 dimensi
arr = np.arange(9) 
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
arr.min() #Nilai array terkecil

0

In [29]:
arr.argmax() #index nilai terbesar

8

In [30]:
arr.argmin() #index nilai terkecil

0

In [33]:
arr.sum() #Menjumlahkan semua array

36

In [32]:
arr.reshape(3,3) #merubah tampilan array 1 dimensi menjadi 2 dimensi

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])