In [1]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[8] #mendapatkan nilai dari sebuah index array

8

In [5]:
arr[0:3] #mendapatkan nilai dari jarak index

array([0, 1, 2])

In [6]:
arr[0] = 9 #merubah data array numpy angka 0 menjadi 9
arr

array([9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[0:5] = 1 #merubah data array numpy dari index 0 sampai 4
arr

array([1, 1, 1, 1, 1, 5, 6, 7, 8, 9])

In [8]:
data = arr[0:5] #menampilkan index 0 sampai 4
data

array([1, 1, 1, 1, 1])

In [9]:
data[:] = 11 #: merubah semua data array : menunjukan semua
data

array([11, 11, 11, 11, 11])

In [10]:
arr

array([11, 11, 11, 11, 11,  5,  6,  7,  8,  9])

In [11]:
#menduplikasi suatu data pada numpy agar bisa di rubah datanya
newData = arr.copy() #dibuat copy dahulu utk melakukan perubahan jika data masih diperlukan
newData

array([11, 11, 11, 11, 11,  5,  6,  7,  8,  9])

In [12]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45])) #array 2 dimensi
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [13]:
arr_2d[1] #menampilkan array 2 dimensi index ke 1 atau baris ke 1

array([20, 25, 30])

In [14]:
arr_2d[0] #menampilkan array 2 dimensi index 0

array([ 5, 10, 15])

In [15]:
arr_2d[2][1] #menampilkan array 2 dimensi indek ke 2 kolom ke 1

40

In [16]:
arr_2d[1][2] #menampilkan array 2 dimensi index ke 1 kolom ke 2

30

In [22]:
arr_2d[2,2] #menampilkan array 2 dimensi index ke 2 kolom ke 2 *untuk array kecil saja

45

In [38]:
#menampilkan array berdasarkan rangenya dimana:
# 0:2 adalah menampilkan index 0 sampai dengan index dibawah 2
# 1:3 adalah menampilkan kolom 1 sampai dengan kolom dibawah 3 
arr_2d[0:2,1:3]

array([[10, 15],
       [25, 30]])

In [39]:
# :2 dapat diartikan menampilkan index yang di bawah dari index 2 berarti index 0 dan index 1
# 1: dapat diartikan menampilkan kolom 1 atau yang di atas dari kolom 1 berarti kolom 2
arr_2d[:2,1:] #:2 batas, 1: angka awal

array([[10, 15],
       [25, 30]])

In [40]:
# SELEKSI DATA

In [41]:
nilai = np.arange(1,11)

In [42]:
nilai

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
nilai > 5 #menseleksi data array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [44]:
nilai[nilai > 5] #menseleksi data array

array([ 6,  7,  8,  9, 10])

In [45]:
nilai + nilai 

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [46]:
nilai * nilai

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [47]:
nilai - nilai

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
nilai / nilai

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])